[versions]
kotlin = "2.2.20"
ktor = "3.3.0"
mcpSdk = "0.8.1"
kotlinLogging = "7.0.3"
slf4j = "2.0.16"

[libraries]
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

# Ktor Server
ktorServerCore = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktorServerSse = { module = "io.ktor:ktor-server-sse", version.ref = "ktor" }
ktorServerSessions = { module = "io.ktor:ktor-server-sessions", version.ref = "ktor" }
ktorServerTests = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }

# MCP SDK
mcpSdk = { module = "io.modelcontextprotocol:kotlin-sdk", version.ref = "mcpSdk" }

# Logging
kotlinLogging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlinLogging" }
slf4jSimple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
